## SIMULATION ##
run_mode			            overwrite
root_dir			            ./root_directory/out
#filename				          candApp_r%'2'1_V%'2'2
filename				          root_directory
					
replicates			          1
generations			          11000 ## 10k burn-in where phenotypic optumum is 0

## POPULATION ##    
patch_number			        2304
patch_capacity			      5


## LIFE CYCLE EVENTS ##
breed_selection_disperse  1    # compact life cycle for constant-size populations
aging					            2
save_stats				        3    # stats and files are recorded/written after aging
save_files				        4    # only adults remain after aging
store							        5

files_sample_size         1  # in each deme and each sex (and each age class), for genotype files

## DISPERSAL ##
breed_disperse_matrix 		&./root_directory/disp_mat.txt

## MATING SYSTEM ##
mating_system				      1

## STORE
store_dir                 binary
store_generation          11000

## QUANTITATITRAIT ##
quanti_init_model                 2
quanti_traits				              1
quanti_pleiotropy                 n
quanti_loci			    	            200
quanti_mutation_rate		          1e-7 ## 
quanti_allele_model			          diallelic
quanti_allele_value			          &./root_directory/allelic_values.txt


## GENETIC MAP ##
quanti_genetic_map                &./root_directory/map_QTN.txt
quanti_genetic_map_resolution     m_r # 

## QUANTI OUTPUT ##
quanti_dir              	        quanti
quanti_output					            genotype ## saves allelic values but not alleles or positions
quanti_logtime					          {{11000}}

#quanti_ohta_output
#quanti_ohta_logtime 		     {{100,9999, 10100, 10500, 11000, 12000, 13000, 14000, 15000}}

## NTRL MARKERS ##
ntrl_loci			   			        199800 ## depends on map
ntrl_all						          2    
ntrl_mutation_rate			      5e-7
ntrl_mutation_model			      1
ntrl_genetic_map              &./root_directory/map_ntrl.txt
ntrl_genetic_map_resolution   m_r ## should match quanti_genetic_map_resolution!

ntrl_init_model					      0
ntrl_save_genotype				    TAB
ntrl_output_dir					      ntrl
ntrl_output_logtime				    {{11000}}


## SELECTION ##
selection_trait					        quant
selection_model                 gaussian
selection_trait_dimension       1
selection_variance              sel_var
selection_local_optima          (@g0 {{1}}, @g10000 &./root_directory/env.txt)

## STAT OUTPUT ##
stat						              	demography adlt.fstat adlt.quanti adlt.quanti.patch adlt.fitness.patch fitness
stat_log_time		        	      100
stat_output_compact
