############################################################
##  Simulated data analyses: LD-scaled genome scans
##
##  This script performs the full downstream analysis and
##  benchmarking of simulated genomic data used in the study.
##
##  Overview:
##  - Input data consist of parsed simulation outputs with
##    genotypes for 500 individuals per replicate.
##  - A fixed subset of 125 individuals is selected to match
##    empirical sampling design and reduce computational load.
##
##  For each simulation replicate, the script:
##    1) Estimates chromosome-specific LD-decay curves
##    2) Performs genotype–environment association analyses
##       using EMMAX and LFMM
##    3) Applies LD-scaling to association statistics (F′)
##    4) Defines outlier regions (ORs) using single-linkage
##       clustering across thousands of random parameter draws
##    5) Integrates evidence across draws using consistency
##       scores (C)
##    6) Assigns focal QTNs to ORs based on LD and distance
##    7) Quantifies performance using OR-level precision,
##       recall, and AUC-based robustness metrics
##
##  Because the simulations have known ground truth (QTNs),
##  this framework allows direct classification of true and
##  false positive outlier regions and systematic benchmarking
##  of LD-scaled vs. SNP-level inference.
##
##  Output:
##  - Intermediate results are saved to ./results_sim/
##  - Aggregated performance metrics and summary tables are
##    saved to ./data/ and reused by plotting scripts
##
##  Notes:
##  - Core functions used here are shared with empirical
##    analyses and form the basis of the LDscanR package.
##  - Simulation-specific helper functions are defined locally
##    and are not part of the package API.
############################################################
## WARNING: This script is computationally intensive and
## intended to be run on a multicore system or HPC cluster.
## Enough example data in ./parsed_data/ (one simulation replicate) 
## for the code to work

#----------------------------------------------------------
#  Load packages
#----------------------------------------------------------

library(data.table)
library(effectsize)
library(scales)
library(tidyr)
library(knitr)
library(pracma)
library(factoextra)
library(parallel)
library(wesanderson)
library(LEA)
library(egg)
library(ggridges)
library(igraph)
library(dplyr)
library(SNPRelate)
library(stats)
library(ggplot2)
library(SNPRelate)
library(data.table)
library(ggplot2)
library(ggsci)


#----------------------------------------------------------
#  Load functions, these are general and are necessary/used for both simulated and empirical data
#  These are the core functions that will be included in the forthcoming LDscnR R-package
#----------------------------------------------------------

invisible(lapply(c("./R/emmax.R",                  ## EMMAX analyses
                   "./R/scale_F_with_ldw.R",       ## LD-scaling
                   "./R/coef_ld_dec.R",            ## helper for estimating LD-decay
                   "./R/get_bg_ld.R",              ## get background LD
                   "./R/get_C.R",                  ## Retrieves C-values from OR-data   
                   "./R/get_el.R",                 ## Helper function to get edge list from gds file
                   "./R/get_ld_w_draws.R",         ## Generates w for ld_w for drawn w-values
                   "./R/ld_decay.R",               ## Estimate LD-decay
                   "./R/ORs_from_draws.R",         ## Gets outlier regions from drawn values
                   "./R/plot_manhattan.R",         ## Function for manhattan plots
                   "./R/SLC.R",                    ## Single linkage clustering
                   "./R/d_from_rho.R"),            ## Distance in bp based on rho
                 source))

#----------------------------------------------------------
#  Functions specific for analysing simulated data, will not be part of the LDscnR package
#----------------------------------------------------------


### --- Get focal QNT for a given SNP --- ###
#   gds - gds file generated by SNPrelate
#   map - The corresponding map file that contains at least columns "marker" 
#     "and "type" where type=="QTN" are the potential focal QTN


focal_QTN <- function(gds,map){
  ids <- read_gds_ids(gds)
  rbindlist(
    lapply(unique(ids$snp_chr), function(ch) {
      
      # SNPs on this chromosome in the GDS
      idx_chr      <- which(ids$snp_chr == ch)
      snp_ids_chr  <- ids$snp_id[idx_chr]
      
      # All SNPs on this chromosome in the map
      map_chr      <- map[Chr == ch]
      markers_chr  <- map_chr$marker
      
      # QTNs on this chromosome
      qtn_chr      <- map_chr[type == "QTN", marker]
      
      # If no QTNs on this chromosome: everything is "not in LD"
      if (length(qtn_chr) == 0L) {
        return(data.table(
          Chr              = ch,
          marker           = markers_chr,
          max_LD_with_QTN  = 0,
          focal_QTN        = NA_character_,
          bp_to_focal_QTN  = NA_real_
        ))
      }
      
      # Full LD matrix (r^2) for this chromosome
      ld_obj  <- snpgdsLDMat(
        gds,
        snp.id     = snp_ids_chr,
        method     = "r",
        slide      = -1,
        num.thread = 8,
        verbose    = FALSE
      )
      LDmat <- ld_obj$LD^2
      dimnames(LDmat) <- list(snp_ids_chr, snp_ids_chr)
      
      # Sub-matrix: rows = QTNs, cols = all SNPs on this chromosome
      ld_sub <- LDmat[qtn_chr, markers_chr, drop = FALSE]
      
      # For each SNP (column), get max LD with any QTN and the QTN giving that max
      max_ld    <- apply(ld_sub, 2, max, na.rm = TRUE)
      focal_idx <- apply(ld_sub, 2, which.max)
      focal_qtn <- qtn_chr[focal_idx]
      
      # Position lookup (use 'Pos' or 'bp' depending on your map)
      pos_vec <- map_chr$Pos   # or map_chr$bp
      names(pos_vec) <- map_chr$marker
      
      bp_to_focal <- abs(pos_vec[markers_chr] - pos_vec[focal_qtn])
      
      data.table(
        Chr             = ch,
        marker          = markers_chr,
        max_LD_with_QTN = max_ld,
        focal_QTN       = focal_qtn,
        bp_to_focal_QTN = bp_to_focal
      )
    }),
    fill = TRUE
  )
}


### --- Extract PR from OR data --- ###
#   OR_data - data generated by function get_ORs_for_draw
#   SNP results (contains relevant q-values and F-values for outlier analyses)
#   ld_test_th - LD threshold defining true positive (in LD-decay units, rho)
#   d_test_th - distance threshold defining true positive (in LD-decay units, rho)
#   p_Va_th - Threshold for defining true positive focal QTn
###
get_PR_data <- function(OR_data,SNP_res,ld_test_th=0.75,d_test_th=0.95,p_Va_th=0.05){
  ors <- unlist(OR_data$ORs,recursive = FALSE)
  
  if(length(na.omit(ors))!=0){
    #or <- ors[[1]]
    OR_focals <- unlist(lapply(ors,function(or){
      
      unique(SNP_res[marker %in% or & 
                       rho_ld<ld_test_th & 
                       rho_d<d_test_th][which.min(rho_ld),focal_QTN])
      
    }))
    
    OR_focals <- unique(OR_focals)  
    
    true <- SNP_res[p_Va>p_Va_th,unique(focal_QTN)] 
    
    true_OR_focals <- OR_focals[OR_focals %in% true]
    
    TP <- length(true_OR_focals)
    FP <- length(ors) - TP
    FN <- length(which(!true %in% true_OR_focals))
    precision <- TP/(TP+FP)
    recall <- TP/(TP+FN)
    PR = precision*recall
    
    FP_ntrl <- sum(sapply(ors,function(or){
      length(SNP_res[marker %in% or & Chr_type=="ntrl",marker])>0
    }))
    
    return(data.table(OR_data[1,],
                      TP,
                      FP,
                      FN,
                      precision,
                      recall,
                      PR,
                      FP_ntrl,
                      OR_focals=list(OR_focals))) 
  }else{
    
    return(data.table(OR_data[1,],
                      TP=0,
                      FP=0,
                      FN=length(SNP_res[p_Va>p_Va_th,unique(focal_QTN)] ),
                      precision = 0,
                      recall = 0,
                      PR = 0,
                      FP_ntrl = 0,
                      OR_focals= list(NA)))
  }
}


### ---  Get oulier regions from C-scores --- ###
#   rho_ld_lim - ld threshold for defining ORs
#   rho_d_lim - d threshold for defining ORs
#   tau_C_lim - C-threshold for defining outlier SNPs
#   n_rep - number of draws
###

get_ORs_from_C <- function(GTs,
                           map,
                           C_vals,
                           decay_tbl, 
                           rho_ld_lim = list(min=0.5, max=1.0),
                           rho_d_lim = list(min=0.90, max=1.0),
                           tau_C_lim = list(min=1e-6, max=0.5),
                           n_cores=1,
                           n_rep=500
){
  
  ## create gds
  gds_path = tempfile(fileext = ".gds")
  gds <- create_gds_from_geno(geno = GTs, map=map,gds_path)
  on.exit({ snpgdsClose(gds); unlink(gds_path) }, add = TRUE) 
  
  
  ## get outliers
  C_vals <- as.matrix(C_vals)
  ids <- read_gds_ids(gds)
  
  ## Analyse only SNPs that have C>0 for any of the C-scores
  all_outliers <- ids$snp_id[apply(C_vals,1,max)>0]
  
  idx <- which(ids$snp_id %in% all_outliers)
  
  outl_chromosomes <- ids$snp_chr[idx]
  
  chrs <- unique(outl_chromosomes)
  
  ## get LD-edge list for each chromosome
  el_chr <- list()
  
  for(ch in chrs){
    outl_ch <- all_outliers[outl_chromosomes==ch]
    
    el_chr[[ch]] <- get_el(gds = gds,
                           idx =  which(ids$snp_id %in% outl_ch),
                           slide_win_ld = -1, ## user all pairwise comparisons
                           n_cores = n_cores)
  }
  
  el_chr <- rbindlist(el_chr)
  
  ## get ORs
  n_sub <- n_rep/500
  ORs <- list()
  
  for(sub in 1:n_sub){
    cat(paste0(sub/n_sub*100,"%"),"..")
    
    ORs[[sub]] <- rbindlist(mclapply(1:500,function(x){
      tau_C <- runif(1,tau_C_lim$min,tau_C_lim$max)
      rho_ld <- runif(1,rho_ld_lim$min,rho_ld_lim$max)
      rho_d <- runif(1,rho_d_lim$min,rho_d_lim$max)
      
      if(length(el_chr)>0){
        ## get thresholds based on drawn rho values
        d_th_by_chr <- setNames(as.integer(d_from_rho(decay_tbl$summary$a, rho_d)), decay_tbl$summary$Chr)
        ld_th_by_chr <- setNames(decay_tbl$summary$b + (1 - decay_tbl$summary$b) * (1 - rho_ld), decay_tbl$summary$Chr) 
        el_chr[,d_th:=d_th_by_chr[Chr1]]
        el_chr[,ld_th:=ld_th_by_chr[Chr1]]
      }
      
      if (length(el_chr) == 0){
        ORs <- data.table(method=colnames(C_vals),mean_d_th_OR=NA,mean_ld_th_OR=NA,ORs=list(NA))
      } else {
        
        ORs <- rbindlist(lapply(1:ncol(C_vals),function(i){
          
          outl_me <- ids$snp_id[C_vals[,i]>tau_C]
          
          ed <- el_chr[r2 > ld_th & d < d_th & SNP1 %in% outl_me & SNP2 %in% outl_me ,.(SNP1, SNP2)]
          
          if (nrow(ed) < 1){
            return(data.table(method=colnames(C_vals)[i],mean_d_th_OR=mean(el_chr$d_th),mean_ld_th_OR=mean(el_chr$d_th),ORs=list(NA)))
            next
          } 
          
          g <- graph_from_data_frame(ed, directed = FALSE)
          comps <- decompose(g)
          ors <- lapply(comps, function(cc) V(cc)$name)
          
          names(ors) <- seq_len(length(ors))
          
          return(data.table(method=colnames(C_vals)[i],mean_d_th_OR=mean(el_chr$d_th),mean_ld_th_OR=mean(el_chr$ld_th),ORs=list(ors)))
        }))
        
      }
      
      #Return draw
      cbind(tau_C=tau_C,rho_d=rho_d,rho_ld=rho_ld,ORs)
    },mc.cores=n_cores))
  }
  
  return(rbindlist(ORs))
}



### --- Get area under the PR curve (AUC-PR) --- ###
# PR_data generated by function get_PR_data (above)
# n1 and n2 are the number of bootstrap replicates to draw for a smooth AUC-curve
###
get_AUC_OR <- function(PR_data,params, n1=500, n2=500,cores=1){
  
  ## get running maximum
  
  cummax_PR <- rbindlist(mclapply(1:n1, function(x){
    rbindlist(lapply(PR_data[,unique(method)],function(meth){
      cbind(indx=1:n2,method=meth,PR_data[method==meth][sample(1:.N,n2,replace = TRUE),.(value=cummax(PR),rep=x)])    
    }))
  },mc.cores = cores))
  
  AUC_norm <- list()
  AUC <- list()
  
  ## get AUC for each method
  for(meth in cummax_PR[,unique(method)]){
    PR_star <- cummax_PR[ method==meth,mean(value),by=.(method,indx)][,V1]          
    k <- seq_along(PR_star)                    
    AUC_pracma <- trapz(k, PR_star)
    PR_star_max <- trapz(k, c(0,rep(1,(max(k)-1))))
    AUC_norm[[meth]] <- AUC_pracma / PR_star_max
    AUC[[meth]] <- AUC_pracma 
  }
  
  data_auc <- cbind(params,cummax_PR[,.(mean_PR=mean(value)),by=.(method,indx)])
  
  max_PR <- cummax_PR[,max(value),by=method]
  max_PR <- max_PR[match(names(AUC),max_PR$method),V1]
  AUC <- data.table(params, method=names(AUC),AUC=unlist(AUC),AUC_norm=unlist(AUC_norm),max_PR)
  
  return(list(data=data_auc,AUC=AUC))
}

#----------------------------------------------------------
#  Main analyses; outlier analyses on random parameter draws, estimation of LD-decay etc. and getting the C-scores from ORs
#----------------------------------------------------------

# palette for plotting
pal <- wes_palette("Zissou1", 21, type = "continuous")

# parsed files generated by ./R_simulations/Parse_raw_data_sim.R
files <- list.files("./parsed_data/",full.names = TRUE)

# split them into replicates (n=10) with the same landscape but different recombination maps, here only one replicate is provided (full data from Zenondo)
tmp <- do.call(rbind,strsplit(files,"/",fixed=TRUE))[,4]

files_split <- split(files, gsub(".rds","",apply(do.call(rbind,strsplit(tmp,"_",fixed=TRUE))[,2:4],1,paste,collapse="_")))

out_folder <- "./results_sim/"

# These are the pre-drawn individuals used for all
# Note that the parsed data contains data for 500 individuals, and these are a subsample of those
keep_125 <-readRDS("./data/keep_inds_125.rds")
cores <- 8 # cores to use

# res_files <- list.files( "./results_sim/",full.names = TRUE)
# res_files <- res_files[!grepl("PR",res_files)]
# res_files <- res_files[grep("rds",res_files)]

#fil <- files_split[[1]]

if(FALSE){
  message("\n\n#### ==== Starting outlier analyses ==== ####\n\n")
  
  
  for(fil in files_split){
    
    # ------------------------ #
    # Read in and prepare data
    # ------------------------ #
    
    ## read in data
    data <- lapply(fil, function(file) readRDS(file))
    map <- do.call(rbind,lapply(data,function(x)x$map))
    
    ## only if result file does not exist
    if(!file.exists(paste0(out_folder,paste(map[1,.(c,V,rep)],collapse="_"),".rds"))){
      
      GTs <- do.call(cbind,lapply(data,function(x)x$GTs))
      
      #re-label chromosomes since we are concatenating data from 10 replicates
      new_order <- map[,order(Chr_9sp,-as.numeric(factor(Chr_type)))]
      GTs <- GTs[,new_order]
      setorder(map,Chr_9sp,Chr_type)
      levs <- map[!duplicated(paste(Chr_9sp,Chr_type))][,paste(Chr_9sp,Chr_type)]
      map[,LG:=as.numeric(factor(paste(Chr_9sp,Chr_type),levels=levs))]
      map[,Chr:=paste0("Chr",LG)]
      map[,marker:=paste(Chr,bp,sep=":")]
      setnames(map,"bp","Pos")
      env_ind <- data[[1]]$env[keep_125]
      env <- data[[1]]$env$env
      
      ## subsample -> reduce from 500 to 125 individuals
      env <- env[keep_125]
      GTs <- GTs[keep_125,]
      
      ## remove duplicate loci
      GTs <- GTs[,map[,which(!duplicated(marker))]]
      map <- map[!duplicated(marker)]
      
      ## recalculate maf for the subsample and filter anew
      
      maf_new <- colSums(GTs)/nrow(GTs)
      maf_new <- ifelse(maf_new<0.5,maf_new,1-maf_new)
      map[,maf:=maf_new]
      GTs <- GTs[,maf_new>0.05]
      map <- map[maf>0.05]
      
      
      ## generate gds file
      gds_path = tempfile(fileext = ".gds")
      gds <- create_gds_from_geno(geno = GTs, map=map,gds_path)
      
      ## close at exit
      on.exit({ snpgdsClose(gds); unlink(gds_path) }, add = TRUE) 
      
      ids <- read_gds_ids(gds)
      
      qtn_rows <- map[,which(type=="QTN")]
      ## compute Va
      va <- sapply(qtn_rows, function(i){
        a  <- map$allelic_values[i]               # effect size α
        gt <- GTs[, i, drop=TRUE]                 # genotype 0/1/2
        p  <- mean(gt)/2                          # allele frequency
        2 * p * (1 - p) * a^2                     # Va formula
      })
      
      ## assign
      map[qtn_rows, Va := va]
      
      ## total Va per chromosome
      map[qtn_rows, sum_Va := sum(Va), by = Chr_9sp]
      
      ## proportion
      map[qtn_rows, p_Va := Va / sum_Va]
      
      
      # -------------------------------------------------- #
      # Core analyses; LD-decay, LD-pruning, EMMAX and LFMM
      # -------------------------------------------------- #
      
      message("Chromosome-vise analyses \n")
      decay_tbl <- list()
      # ch = unique(map$Chr_9sp)[1]
      for(ch in unique(map$Chr_9sp)){
        idx <- which(map$Chr_9sp==ch)
        
        ## Estimate LD-decay for chromosomes 
        decay_tbl[[ch]] <- ld_decay(gds=NULL,
                                    geno=GTs[,idx],
                                    map = map[idx],
                                    q = 0.95,
                                    n_sub = 5000,
                                    slide_win_ld = 1000,
                                    window_size = 1e6,
                                    step_size = 5e5,
                                    n_cores_ld =  cores)
        
        ## LD pruning
        
        ## Single linkage clustering based on q=0.5 (half-way decay distance)
        cls <- SLC(gds,decay_tbl = decay_tbl[[ch]],idx = idx,slide_win_ld = 1000,q = 0.5)$CLS 
        
        pruned_SNPs <- sapply(cls,sample,1) ## from clusters, pick one randomly
        
        ### === EMMAX analyses based on LD-pruned data === ###
        
        ## GRM based on pruned SNPs
        
        GRM <- snpgdsGRM(gds,method = "GCTA",verbose = FALSE,snp.id = pruned_SNPs,autosome.only = FALSE)$grm
        
        ## EMMAX does not expect a file in 012 format so the maximum likelihood genotypes can be used (without rounding)
        emx <- emmax(env,GTs[,idx],K = GRM) 
        
        map[idx,emx_F:=emx$F] ## add to map
        emx_gif = map[idx,median(emx_F)/qf(0.5,1,nrow(GTs)-2,lower.tail = FALSE)] ## inflation factor
        map[idx,emx_F:=emx_F/emx_gif]  ## genomic control
        
        ### === Latent factor mixed model analyses (LFMM) === ###
        
        ## get K
        xxx.pca1 <- prcomp(GTs[,idx], center=FALSE, scale.=FALSE, rank. = 10) # stats::
        results <- xxx.pca1$x
        km1<- eclust(results, "kmeans", hc_metric="eucliden",verbose = FALSE,graph = FALSE)
        
        ## LFMM
        write.lfmm(GTs[,idx], "./tmp/genotypes.lfmm")
        write.env(env, "./tmp/gradients.env")
        project = NULL
        
        project = lfmm2("./tmp/genotypes.lfmm", "./tmp/gradients.env", K=length(unique(km1$cluster))) # K is user defined
        pv = suppressWarnings(lfmm2.test(project, "./tmp/genotypes.lfmm", "./tmp/gradients.env",genomic.control = TRUE,full = TRUE))
        
        ## save F-value corrected for inflation
        map[idx,lfmm_F:=pv$fscores/pv$gif]
      }
      
      
      ## collect LD-decay data 
      decay_tbl_final <- list()
      decay_tbl_final$data <- rbindlist(lapply(decay_tbl,function(x) x$data))
      decay_tbl_final$summary <- rbindlist(lapply(decay_tbl,function(x) x$summary))
      
      ## generate ld_w for draws
      
      message("Draw ld_w \n")
      ld_w_draws <- get_ld_w_draws(gds,decay_tbl = decay_tbl_final,slide_win_ld = 1000,n_draws = 200,min = 0.75,max = 1,n_cores = cores)
      
      cat("get ORs from draws \n")
      
      df2 = n_inds-2
      q_orgs <- apply(F_vals,2,function(Fval){
        p <- pf(Fval, df1=1, df2, lower.tail = FALSE)
        q <- p.adjust(p,"fdr")
      })
      colnames(q_orgs) <- c("emx_q","lfmm_q")
      
      ## get ORs for draws; 200 ld_w vectors and 25 randomly sampled parameter values for each of them
      ORs_for_Cscore <- get_ORs_for_draw(gds,
                                         F_vals = map[,.(emx_F,lfmm_F)],
                                         q_orgs = q_orgs,
                                         decay_tbl = decay_tbl_final,
                                         ld_w_draws = ld_w_draws,
                                         n_inds=nrow(GTs),
                                         n_draws = 25,
                                         rho_OR_lim = NULL,
                                         rho_ld_lim = list(min=0.5, max=1.0),
                                         rho_d_lim = list(min=0.90, max=1.0),
                                         alpha_lim = list(min=-log10(0.05), max=4),
                                         lmin_lim = list(min=1, max=10),
                                         n_cores = 8)
      
      ## get C-score and collect data
      map <- cbind(map, get_C(draws = ORs_for_Cscore,markers = map$marker))
      
      map <- cbind(map,q_orgs)
      
      # ---------------------------------- #
      # Get focal QTN and associated data
      # ---------------------------------- #
      message("Get focal QTN \n")
      foc_QTN <- focal_QTN(gds,map)
      
      ## collect data
      map[,max_LD_with_QTN:=foc_QTN$max_LD_with_QTN]
      map[,bp_to_focal_QTN:=foc_QTN$bp_to_focal_QTN]
      map[,focal_QTN:=foc_QTN$focal_QTN]
      map[type=="QTN",max_LD_with_QTN:=1]
      map[type=="QTN",bp_to_focal_QTN:=0]
      map[Chr_type=="ntrl",bp_to_focal_QTN:=max(Pos)]
      map[Chr_type=="ntrl",max_LD_with_QTN:=0]
      map[type=="QTN",focal_QTN:=marker]
      
      ## add decay info
      as <- setNames(decay_tbl_final$summary$a,decay_tbl_final$summary$Chr)
      bs <- setNames(decay_tbl_final$summary$b,decay_tbl_final$summary$Chr)
      map[,a := as[Chr]]
      map[,b := bs[Chr]]
      
      ## calculate distance to focal QTN expressed in LD-scaled units (rho)
      map[,rho_d := a*bp_to_focal_QTN/(a*bp_to_focal_QTN+1)]
      map[,rho_ld := 1-(max_LD_with_QTN-b)/(1 - b)]
      
      ## save data
      out <- list(SNP_res=map,GTs=GTs,ORs_for_Cscore=ORs_for_Cscore,decay_tbl=decay_tbl_final)
      base_name <- paste(map[1,.(c,V,rep)],collapse="_")
      
      saveRDS(out,paste0(out_folder,paste(map[1,.(c,V,rep)],collapse="_"),".rds"))
    }else{
      cat(paste(map[1,.(c,V,rep)],collapse="_"),"Already done \n")
    }
  }  
}

cat("\n\n#### ==== Done with outlier analyses ==== ####\n\n")


#----------------------------------------------------------
#  Get true and false positive ORs (PR-data) that is used to estimate AUC
#----------------------------------------------------------


message("\n\n#### ==== Getting true anf false positive ORs ==== ####\n\n")

out_folder <- "./results_sim/"

res_files <- list.files(out_folder,full.names = TRUE)
done <- res_files[grepl("_PR.rds",res_files)]

res_files <- res_files[!grepl("PR",res_files)]
res_files <- res_files[grep("rds",res_files)]
#res_file <- res_files[1]

ld_test_th <- 0.75
d_test_th <- 0.95
p_Va_th <- 0.05
n_rep_C = 5000

if(TRUE){
  for(res_file in res_files){
    message("Working on ",res_file)
    data <- readRDS(res_file)
    
    ## split data for parallel analyses
    ORs <- split(data$ORs_for_Cscore,rep(1:(nrow(data$ORs_for_Cscore)/1000),each=1000))
    n_sub <- length(ORs)
    
    PR_data <- list()
    
    message("Getting PR from original ORs \n")
    for(sub in 1:n_sub){
      cat(paste0(round(sub/n_sub*100),"%"),"..")
      
      PR_data[[sub]] <- rbindlist(mclapply(1:nrow(ORs[[sub]]),function(x){
        get_PR_data(OR_data = ORs[[sub]][x],SNP_res=data$SNP_res,ld_test_th=ld_test_th,d_test_th=d_test_th,p_Va_th=p_Va_th)  
      },mc.cores = cores))  
      
    }
    
    PR_data <- rbindlist(PR_data)
    
    ## now get ORs based on C-values (replacing l_min, rho_w and alpha)
    message("Getting PR from C-scores")
    
    C_vals <- data$SNP_res[1:.N,grep("C_",colnames(data$SNP_res)),with = FALSE]
    
    ORs <- get_ORs_from_C(GTs=data$GTs,
                          map=data$SNP_res,
                          C_vals=C_vals,
                          decay_tbl = data$decay_tbl,
                          rho_ld_lim = list(min=0.5, max=1.0),
                          rho_d_lim = list(min=0.90, max=1.0),
                          tau_C_lim = list(min=1e-6, max=0.5),
                          n_cores=cores,
                          n_rep = n_rep_C)
    
    
    
    ORs <- split(ORs,rep(1:(nrow(ORs)/1000),each=1000))  
    n_sub <- length(ORs)
    
    ## PR from C-scores
    PR_data_C <- list()
    for(sub in 1:n_sub){
      cat(paste0(round(sub/n_sub*100),"%"),"..")
      
      PR_data_C[[sub]] <- rbindlist(mclapply(1:nrow(ORs[[sub]]),function(x){
        
        get_PR_data(OR_data = ORs[[sub]][x],SNP_res=data$SNP_res,ld_test_th=ld_test_th,d_test_th=d_test_th,p_Va_th=p_Va_th)  
        
      },mc.cores = cores))  
    }
    
    PR_data_C <- rbindlist(PR_data_C)
    
    ## save data in same folder with _PR suffix
    saveRDS(list(PR_data=PR_data,
                 PR_data_C=PR_data_C,
                 ORs=data$ORs_for_Cscore,
                 ORs_C=rbindlist(ORs)),
            paste0(out_folder,paste(data$SNP_res[1,.(c,V,rep)],collapse="_"),"_PR.rds"))
    
  }  
}  

#----------------------------------------------------------
#  Calculating AUC based on PR-data
#----------------------------------------------------------

message("\n\n#### ==== Attaining AUC data ==== ####\n\n")


res_files <- list.files( "./results_sim/",full.names = TRUE)
PR_files <- res_files[grepl("_PR.rds",res_files)]

#PR_file <- PR_files[1]
if(!file.exists("./data/PR_AUC_data.rds")){
  PR_AUC_data <- list()
  
  for(PR_file in PR_files){
    print(PR_file)
    base_name <- gsub("_PR.rds","",do.call(rbind,strsplit(PR_file,"//"))[,2])
    PR_OGR <- readRDS(PR_file)
    
    pars <- data.table(do.call(rbind,strsplit(base_name,"_")))
    setnames(pars,colnames(pars),c("c","V","rep"))
    
    dt <- rbind(PR_OGR$PR_data_C,PR_OGR$PR_data,fill=TRUE,use.names=TRUE)
    AUC <- get_AUC_OR(dt,pars,n1=500,n2=500,cores = 8)
    
    AUC$AUC <- cbind(AUC$AUC,mean_PR=dt[,.(mean_PR=mean(PR)),by=method][,mean_PR])
    
    PR_AUC_data[[PR_file]] <- AUC
    
  }
  
  
  
}




data_AUC <- rbindlist(lapply(readRDS("./data/PR_AUC_data.rds"),function(x)x$AUC))

### === clean up names === ###  
par_map <- data.table(
  c = c("c1","c1.5","c2"),
  gene_flow = c("High","Medium","Low")
)

data_AUC[,gene_flow:=par_map$gene_flow[match(c,par_map$c)]]

par_map <- data.table(
  V = c("V0.5","V1","V2"),
  selection_intensity = c("Strong","Medium","Weak")
)

data_AUC <- merge(data_AUC, par_map, by="V", all.x=TRUE)

data_AUC[,gene_flow:=factor(gene_flow,levels=c("High","Medium","Low"))]

data_AUC[,selection_intensity:=factor(selection_intensity,levels=c("Strong","Medium","Weak"))]

par_map <- data.table(
  method = c("emx_F","lfmm_F","emx_F_prime","lfmm_F_prime","joint","C_emx_F","C_lfmm_F","C_emx_F_prime","C_lfmm_F_prime","C_joint"),
  Method = c("EMX","LFMM","EMX´","LFMM´","Joint","EMX-C","LFMM-C","EMX´-C","LFMM´-C","Joint-C")
)

data_AUC[,Method:=par_map$Method[match(method,par_map$method)]]

data_AUC[,AUC_meth := ifelse(grepl("C",method,fixed = TRUE),"PR[C]","PR^'*'")]
data_AUC[,Method:=factor(Method,levels=c("EMX","EMX-C","LFMM","LFMM-C","EMX´","EMX´-C","LFMM´","LFMM´-C","Joint","Joint-C"))]

data_AUC[,sim:=factor(paste(gene_flow,selection_intensity,sep="\n"))]

data_AUC[,sim:=factor(sim,levels = levels(sim)[c(2,1,3,8,7,9,5,4,6)])]

par_map <- data.table(
  method = c("emx_F","lfmm_F","emx_F_prime","lfmm_F_prime","joint","C_emx_F","C_lfmm_F","C_emx_F_prime","C_lfmm_F_prime","C_joint"),
  base_method = c("EMX","LFMM","EMX´","LFMM´","Joint","EMX","LFMM","EMX´","LFMM´","Joint")
)

data_AUC[,base_method:=par_map$base_method[match(method,par_map$method)]]



data_AUC[,base_method:=factor(base_method,levels=c("EMX",
                                                   "LFMM",
                                                   "EMX´",
                                                   "LFMM´",
                                                   "Joint"))]

data_AUC[,R:=AUC_norm/max_PR]
data_AUC[is.nan(R),R:=0]
data_AUC[,AUC_meth:=factor(AUC_meth,levels=c("PR^'*'","PR[C]"))]

saveRDS(data_AUC,"./data/data_AUC.rds") 

#----------------------------------------------------------
#  Get data for all draws
#----------------------------------------------------------

message("\n\n#### ==== Parsing and saving data for all draws ==== ####\n\n")

if(!file.exists("./data/all_draws.rds")){
  all_draws <- list()
  all_qtn <- list()
  
  for (PR_file in PR_files) {
    cat("Working on", PR_file, "\n")
    
    base_name <- sub("_PR\\.rds$", "", basename(PR_file))
    
    PR_OGR <- readRDS(PR_file)
    PR_data <- rbindlist(list(PR_OGR$PR_data, PR_OGR$PR_data_C), fill = TRUE)
    
    data_path <- res_files[grep(paste0(base_name, "."), res_files, fixed = TRUE)][1]
    data <- readRDS(data_path)
    
    SNP_res <- data$SNP_res
    
    OR_focals <- PR_data$OR_focals
    lens <- lengths(OR_focals)
    
    # Map focal markers -> p_Va (list column aligned to OR_focals)
    pVa_vec <- SNP_res[match(unlist(OR_focals), marker), p_Va]
    pVa_list <- split(pVa_vec, rep(seq_along(OR_focals), times = lens))
    
    # ensure length alignment (including empty OR_focals)
    pVa_full <- vector("list", length(OR_focals))
    pVa_full[lens != 0L] <- pVa_list
    
    PR_data[, p_Va := pVa_full]
    
    # add scenario identifiers once
    meta <- SNP_res[1, .(c, V, rep)]
    
    all_draws[[PR_file]] <- cbind(meta, PR_data)
    
    # store all QTN p_Va for baseline distribution
    all_qtn[[PR_file]] <- cbind(
      meta,
      data.table(method = "all_QTN", p_Va = list(SNP_res[type == "QTN", p_Va]))
    )
  }
  
  all_draws <- rbindlist(all_draws, fill = TRUE)
  all_qtn <- rbindlist(all_qtn, fill = TRUE)
  
  par_map <- data.table(
    c = c("c1","c1.5","c2"),
    gene_flow = c("High","Medium","Low")
  )
  
  all_draws[,gene_flow:=par_map$gene_flow[match(c,par_map$c)]]
  
  par_map <- data.table(
    V = c("V0.5","V1","V2"),
    selection_intensity = c("Strong","Medium","Weak")
  )
  
  all_draws <- merge(all_draws, par_map, by="V", all.x=TRUE)
  
  all_draws[,gene_flow:=factor(gene_flow,levels=c("High","Medium","Low"))]
  
  all_draws[,selection_intensity:=factor(selection_intensity,levels=c("Strong","Medium","Weak"))]
  
  par_map <- data.table(
    method = c("emx_F","lfmm_F","emx_F_prime","lfmm_F_prime","joint","C_emx_F","C_lfmm_F","C_emx_F_prime","C_lfmm_F_prime","C_joint"),
    Method = c("'EMX'","'LFMM'","'EMX´'","'LFMM´'","'Joint'","'EMX-C'","'LFMM-C'","'EMX´-C'","'LFMM´-C'","'Joint-C'")
  )
  
  all_draws[,Method:=par_map$Method[match(method,par_map$method)]]
  
  all_draws[,AUC_meth := ifelse(grepl("C",method,fixed = TRUE),"PR[C]","PR^'*'")]
  all_draws[,Method:=factor(Method,levels=c("'EMX'","'EMX-C'","'LFMM'","'LFMM-C'","'EMX´'","'EMX´-C'","'LFMM´'","'LFMM´-C'","'Joint'","'Joint-C'"))]
  
  all_draws[,sim:=factor(paste(gene_flow,selection_intensity,sep="\n"))]
  
  all_draws[,sim:=factor(sim,levels = levels(sim)[c(2,1,3,8,7,9,5,4,6)])]
  
  par_map <- data.table(
    method = c("emx_F","lfmm_F","emx_F_prime","lfmm_F_prime","joint","C_emx_F","C_lfmm_F","C_emx_F_prime","C_lfmm_F_prime","C_joint"),
    base_method = c("'EMX'","'LFMM'","'EMX´'","'LFMM´'","'Joint'","'EMX'","'LFMM'","'EMX´'","'LFMM´'","'Joint'")
  )
  
  all_draws[,base_method:=par_map$base_method[match(method,par_map$method)]]
  
  all_draws[,base_method:=factor(base_method,levels=c("'LFMM'",
                                                      "'LFMM´'",
                                                      "'EMX'",
                                                      "'EMX´'",
                                                      "'Joint'"))]
  ## files already exist
  saveRDS(all_draws,"./data/all_draws.rds")
  saveRDS(all_qtn,"./data/all_qtn.rds")
}

#----------------------------------------------------------
#  Get to 10& from all draws
#----------------------------------------------------------

message("\n\n#### ==== Extracting and saving top 10% data ==== ####\n\n")

## note that the file all_draws.rds is too big to be included here and is available
## from Zenondo
if(!any("all_draws"==ls())){ all_draws <- readRDS("./data/all_draws.rds")}

K=500 # 10% of 5000 draws

top_10 <- all_draws[
  # random order within each group (tie-break)
  , .SD[sample.int(.N)][order(-PR)][seq_len(min(K, .N))]
  , by = .(sim, Method, AUC_meth,rep)
]

saveRDS(top_10,"./data/top_10.rds")

